import { StyleSheet, Dimensions } from 'react-native';
import { colors, typography, spacing, dimensions } from '../../theme/materialDesign';

const { width } = Dimensions.get('window');

export const styles = StyleSheet.create({
    safeArea: {
        flex: 1,
    },
    container: {
        flex: 1,
    },
    header: {
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.sm,
        alignItems: 'center',
        backgroundColor: colors.surface + '95',
        borderBottomWidth: 1,
        borderBottomColor: colors.primary + '20',
    },
    titleText: {
        ...typography.h3,
        color: colors.onSurface,
        textAlign: 'center',
        fontWeight: '700',
        fontSize: 20,
    },
    createPostContainer: {
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.xs,
        backgroundColor: 'transparent',
    },
    createPostCard: {
        padding: spacing.md,
        backgroundColor: colors.surface + 'F8',
        borderWidth: 2,
        borderColor: colors.primary + '40',
        marginBottom: spacing.sm,
    },
    createPostTitle: {
        ...typography.body1,
        color: colors.onSurface,
        fontWeight: '600',
        marginBottom: spacing.sm,
        textAlign: 'center',
        fontSize: 14,
    },
    postInput: {
        backgroundColor: colors.surface,
        borderWidth: 2,
        borderColor: colors.primary + '50',
        borderRadius: 16,
        padding: spacing.md,
        ...typography.body2,
        color: colors.onSurface,
        minHeight: 80,
        maxHeight: 120,
        textAlignVertical: 'top',
        marginBottom: spacing.md,
        fontSize: 14,
        lineHeight: 20,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    postActions: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingTop: spacing.sm, // Increased for better spacing
        marginTop: spacing.xs,
    },
    characterCount: {
        ...typography.caption,
        color: colors.onSurfaceVariant,
        fontSize: 11,
    },
    postButton: {
        paddingHorizontal: spacing.lg,
        paddingVertical: spacing.sm,
        minWidth: 90, // Increased for better button size
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.2,
        shadowRadius: 2,
    },
    feedContainer: {
        flex: 1,
        paddingTop: spacing.xs,
    },
    feedContent: {
        paddingHorizontal: spacing.md,
        paddingBottom: spacing.xxl,
    },
    bottomSpacer: {
        height: spacing.xxl * 2,
    },
    postCard: {
        padding: spacing.lg,
        marginBottom: spacing.md,
        minHeight: 100,
    },
    postHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    avatarContainer: {
        width: 40,
        height: 40,
        borderRadius: 20,
        backgroundColor: colors.primary,
        alignItems: 'center',
        justifyContent: 'center',
        marginRight: spacing.md,
        shadowColor: colors.primary,
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.3,
        shadowRadius: 4,
        elevation: 4,
    },
    avatarText: {
        ...typography.body1,
        color: colors.onPrimary,
        fontWeight: '700',
        fontSize: 16,
    },
    postInfo: {
        flex: 1,
    },
    authorName: {
        ...typography.body2,
        color: colors.onSurface,
        fontWeight: '600',
        fontSize: 14,
    },
    postTime: {
        ...typography.caption,
        color: colors.onSurfaceVariant,
        fontSize: 11,
    },
    postContent: {
        ...typography.body2,
        color: colors.onSurface,
        lineHeight: 22,
        marginBottom: spacing.md,
        fontSize: 14,
        letterSpacing: 0.2,
    },
    reactionsDisplay: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.xs,
        marginBottom: spacing.sm,
    },
    reactionChip: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: colors.primary,
        paddingHorizontal: spacing.sm,
        paddingVertical: spacing.xs,
        borderRadius: 12,
        gap: spacing.xs,
    },
    reactionEmoji: {
        fontSize: 14,
    },
    reactionCount: {
        ...typography.caption,
        color: colors.onPrimary,
        fontWeight: '600',
        fontSize: 11,
    },
    actionsContainer: {
        flexDirection: 'row',
        justifyContent: 'flex-start',
    },
    reactButton: {
        paddingHorizontal: spacing.md,
        paddingVertical: spacing.xs,
        backgroundColor: colors.surfaceVariant,
        borderRadius: 16,
    },
    reactButtonText: {
        ...typography.caption,
        color: colors.onSurfaceVariant,
        fontWeight: '500',
        fontSize: 12,
    },
    reactionPicker: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: spacing.sm,
        marginTop: spacing.sm,
        padding: spacing.sm,
        backgroundColor: colors.surfaceVariant,
        borderRadius: 8,
    },
    reactionOption: {
        padding: spacing.xs,
        borderRadius: 16,
        backgroundColor: colors.surface,
        minWidth: 32,
        alignItems: 'center',
    },
    reactionOptionEmoji: {
        fontSize: 18,
    },
    loadingCard: {
        padding: spacing.lg,
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    loadingText: {
        ...typography.body2,
        color: colors.onSurfaceVariant,
        fontStyle: 'italic',
        fontSize: 14,
    },
    emptyCard: {
        padding: spacing.lg,
        alignItems: 'center',
        marginBottom: spacing.md,
    },
    emptyEmoji: {
        fontSize: 40,
        marginBottom: spacing.sm,
    },
    emptyTitle: {
        ...typography.body1,
        color: colors.onSurface,
        fontWeight: '600',
        marginBottom: spacing.xs,
        fontSize: 16,
    },
    emptyText: {
        ...typography.body2,
        color: colors.onSurfaceVariant,
        textAlign: 'center',
        lineHeight: 20,
        fontSize: 14,
    },
});
